### Get blogs
GET http://localhost:3001/api/blogs


### Add new blog:
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Maina",
    "author": "Guillermo Cerviño Porto",
    "url": "https://mainagastronomia.es/",
    "likes": 23
}

### Delete blog:
DELETE http://localhost:3001/api/blogs/6738ec21af719e7c7bdbbeff