### Get blogs
GET http://localhost:3001/api/blogs


### Add new blog:
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vdGFyaW8iLCJpZCI6IjY3M2RkOWZhZDA4MGNlNGY3YjQ1NDAzNSIsImlhdCI6MTczMjEyNzQ1MX0._o95rzfSxleNfLjf40jLL505e0HHKpdu5yFxMi9rpys

{
    
    "author": "Samuel Perez",
    "url": "https://unacualquiera.es/",
    "title": "Un título insulso",
    "likes": 16
}

### Delete blog:
DELETE http://localhost:3001/api/blogs/6738ec21af719e7c7bdbbeff

### AUpdate blog:
PUT http://localhost:3001/api/blogs/6738f4b239a8ddfd482364!!
Content-Type: application/json

{
    "likes": 23
}