### Get blogs
GET http://localhost:3001/api/blogs


### Add new blog:
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNlY3JldGFyaW8iLCJpZCI6IjY3M2UzMGYyYWIyNmVjYTU1NmM0ZGRhYyIsImlhdCI6MTczMjEyOTAyNn0.-_cwfA3bTG6XKCOG8GG2f_LzWeGbyQCLNjcwabZB6r8

{
    
    "author": "Marcos Suarez",
    "url": "https://ejemplo.es/",
    "title": "Ya te digo",
    "likes": 3
}

### Delete blog:
DELETE http://localhost:3001/api/blogs/6738ec21af719e7c7bdbbeff

### AUpdate blog:
PUT http://localhost:3001/api/blogs/6738f4b239a8ddfd482364!!
Content-Type: application/json

{
    "likes": 23
}