### Get users
GET http://localhost:3001/api/users

### Create user:
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Secretario",
    "name": "Mono saltarín",
    "password": "unadetrásdeotra"
}

###Login:
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "username": "Secretario",
    "password": "unadetrásdeotra"
}

