### Get users
GET http://localhost:3001/api/users

### Create user:
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Notario665",
    "name": "Andrés Calamaro",
    "password": "Laquesea"
}